apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: "joindevops/mongodb:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
      volumes:
      - name: mongodb
        persistentVolumeClaim: # this is the PVC
          claimName: ebs-dynamic-pvc