apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  clusterIP: None #headless
  selector:
    app: redis
    tier: db
    project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379 # this port belongs to service
    targetPort: 6379 # this port belongs to container