apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  clusterIP: None #headless
  selector:
    app: rabbitmq
    tier: db
    project: roboshop
  ports:
  - name: rabbitmq-port
    protocol: TCP
    port: 5672 # this port belongs to service
    targetPort: 5672